package main

import (
  "bufio"
  "os"
  "log"
)

func listenStdin (stream *Stream) {
  scanner := bufio.NewScanner(os.Stdin)
  for scanner.Scan() {
    // Switched from Bytes() to Text() because:
    // Bytes returns the most recent token generated by a call to Scan.
    // The underlying array may point to data that will be overwritten
    // by a subsequent call to Scan. It does no allocation.
    line := scanner.Text()
    stream.C <- newEvent(nil, []byte(line[:]))
  }
  if err := scanner.Err(); err != nil {
    log.Fatal(err)
  }
}
